name: Open Journal Preprint
description: Generate preprint LaTeX file
inputs:
  issue_id:
    description: The review issue id for the paper
    required: true
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""
  journal:
    description: The journal data to use for the paper. Default is 'joss'.
    required: false
    default: joss
outputs:
  preprint_file_path:
    description: "Path to the generated preprint file"
    value: ${{ steps.compilation-result.outputs.paper_pdf_path }}
  preprint_file_name:
    description: "Name for the generated preprint file"
    value: ${{ steps.compilation-result.outputs.paper_jats_path }}
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
        cache-version: preprint
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Find paper file
      id: paper-finder
      shell: bash
      env:
        ISSUE_ID: ${{ inputs.issue_id }}
        REPO_URL: ${{ inputs.repository_url }}
        PAPER_BRANCH: ${{ inputs.branch }}
        JOURNAL_ALIAS: ${{ inputs.journal }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/find_paper.rb
    - name: Build preprint
      id: build-preprint
      uses: xuanxu/publishing-artifacts-action@main
      with:
        journal: ${{ inputs.journal_template }}
        paper-path: ${{ steps.paper-finder.outputs.paper_file_path }}
        args: "-o preprint"
    - name: Check preprint
      id: preprint-result
      shell: bash
      run: |
        ruby ${{ github.action_path }}/preprint_result.rb ${{ steps.paper-finder.outputs.paper_file_path }}

branding:
  icon: file-text
  color: blue