name: Open Journal Preprint
description: Generate preprint LaTeX file
inputs:
  issue_id:
    description: The review issue id for the paper
    required: true
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""
  journal:
    description: The journal to use for the preprint. Default is 'joss'.
    required: false
    default: joss
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
        cache-version: preprint
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Prepare data
      id: preprint-data
      shell: bash
      env:
        ISSUE_ID: ${{ inputs.issue_id }}
        REPO_URL: ${{ inputs.repository_url }}
        PAPER_BRANCH: ${{ inputs.branch }}
        JOURNAL_ALIAS: ${{ inputs.journal }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/prepare_preprint_data.rb
    - name: Build preprint
      id: build-preprint
      uses: xuanxu/publishing-artifacts-action@main
      with:
        paper-path: ${{ steps.preprint-data.outputs.paper_file_path }}
        args: ${{steps.preprint-data.outputs.inara_args}}
    - name: Rename file
      id: rename-file
      shell: bash
      env:
        ISSUE_ID: ${{ inputs.issue_id }}
        JOURNAL_ALIAS: ${{ inputs.journal }}
        PAPER_PATH: ${{steps.preprint-data.outputs.paper_file_path}}
      run: |
        ruby ${{ github.action_path }}/rename_preprint_file.rb
    - uses: actions/upload-artifact@v3
      with:
        name: preprint-${{ inputs.journal }}-${{ inputs.issue_id }}
        path: ${{ steps.rename-file.outputs.preprint_file_path }}
        retention-days: 2
branding:
  icon: file-text
  color: blue